### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by NatElkins** [georgewfraser/fsharp-language-server#10]
I tried running the VS Code extension while on Ubuntu, but it failed with the following message:

```
[Error - 2:01:11 PM] Connection to server is erroring. Shutting down server.
[Error - 2:01:11 PM] Connection to server is erroring. Shutting down server.
/home/nat/.vscode/extensions/georgewfraser.fsharp-language-server-0.1.9/src/FSharpLanguageServer/bin/Release/netcoreapp2.0/osx.10.11-x64/publish/FSharpLanguageServer: 1: /home/nat/.vscode/extensions/georgewfraser.fsharp-language-server-0.1.9/src/FSharpLanguageServer/bin/Release/netcoreapp2.0/osx.10.11-x64/publish/FSharpLanguageServer: Syntax error: word unexpected (expecting ")")
```

Is this failing because I'm using Ubuntu instead of OS X?

**Comment by georgewfraser** [comment]
Yes, we just need to add a 3rd build and call it from VSCode. If you feel like setting it up yourself right now, the relevant code is [here](https://github.com/georgewfraser/fsharp-language-server/blob/master/src/FSharpLanguageServer/FSharpLanguageServer.fsproj#L6) and [here](https://github.com/georgewfraser/fsharp-language-server/blob/master/client/extension.ts#L200). Add to both those places, the run scripts/build.sh, then install build.vsix from VSCode using "Install from VSIX" in the extensions `...` menu.

**Comment by georgewfraser** [comment]
I think this works now
