### ISSUE TITLE
Non-NuGet references aren't cracked properly

### ISSUE THREAD

**Issue by inosik** [georgewfraser/fsharp-language-server#11]
The project cracker parses `project.assets.json`, but that file doesn't contain references to assemblies from the GAC or even to local references (e. g. `<Reference Include="libs/lib.dll" />`).

Project file:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <!-- System.ComponentModel.Composition is MEF -->
    <Reference Include="System.ComponentModel.Composition" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
</Project>
```

`Library.fs`:

``` fsharp
module Library
open System.ComponentModel.Composition
let attr = ExportAttribute ()
```

Result:

![Screenshot - Red squiggles](https://user-images.githubusercontent.com/11393003/41656511-7c1ffd90-7490-11e8-977a-1a1bbb9ad04c.png)

**Comment by georgewfraser** [comment]
@inosik  Do you think you could make a minimal example of a project that isn't cracked properly, put it in the sample/ directory, and make a PR? That will be super helpful in troubleshooting, and will make it easy to add a test that verifies the fix, so this problem never regresses.

**Comment by inosik** [comment]
I updated the title and description as this also applies to .NET Core projects.

There's already a disabled test in the `ProjectManagerTests` file, should I still add a sample?

https://github.com/georgewfraser/fsharp-language-server/blob/3435787110e4a01f7a69a3cf946956d69928d069/tests/FSharpLanguageServer.Tests/ProjectManagerTests.fs#L51-L61

**Comment by georgewfraser** [comment]
If it's exactly the same as samples/HasLocalDll, then no need to add another sample. But if you think you have found a variation of the problem that differs in some important way, please add one.

**Comment by inosik** [comment]
I'll just create a PR and let you decide 😄

**Comment by inosik** [comment]
See #12.
