### ISSUE TITLE
Wrong type of function

### ISSUE THREAD

**Issue by hansemandse** [georgewfraser/fsharp-language-server#34]
Issue Type: <b>Bug</b>

Try writing the function shown in the screenshot. When defining it, the language server infers a different (and wrong) type than the one displayed above the function.

Extension version: 0.1.19
VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>

<img width="318" alt="codebug" src="https://user-images.githubusercontent.com/37290815/50149084-7dd82280-02ba-11e9-95b4-e07f012c8f4f.PNG">

**Comment by georgewfraser** [comment]
I think you are using Ionide. F#LS doesn't show those types above the function.
